# ============================ Backtesting Models ============================
"""
Safe historical simulation models.

This module contains no live trading code.
It only describes historical candles, simulated signals, simulated trades,
and backtest reports.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any

from tradingagents.decision import DecisionStatus, SignalDirection


@dataclass(frozen=True)
class BacktestCandle:
    """Single OHLCV candle used by the backtesting engine."""

    timestamp: int
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0

    def __post_init__(self) -> None:
        if self.timestamp <= 0:
            raise ValueError("BacktestCandle.timestamp must be positive.")
        for field_name in ("open", "high", "low", "close"):
            value = getattr(self, field_name)
            if value <= 0:
                raise ValueError(f"BacktestCandle.{field_name} must be positive.")
        if self.volume < 0:
            raise ValueError("BacktestCandle.volume cannot be negative.")

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class BacktestSignal:
    """Simulated strategy signal used for historical testing.

    This is not an order. It is an input to the simulator only.
    """

    asset: str
    timestamp: int
    direction: SignalDirection
    action: DecisionStatus
    confidence_score: int
    risk_score: int
    reason: str = ""

    def __post_init__(self) -> None:
        if not self.asset.strip():
            raise ValueError("BacktestSignal.asset cannot be blank.")
        if self.timestamp <= 0:
            raise ValueError("BacktestSignal.timestamp must be positive.")
        if self.confidence_score < 0 or self.confidence_score > 100:
            raise ValueError("BacktestSignal.confidence_score must be 0-100.")
        if self.risk_score < 0 or self.risk_score > 100:
            raise ValueError("BacktestSignal.risk_score must be 0-100.")

    @property
    def is_trade_candidate(self) -> bool:
        """Only paper/manual review recommendations can be simulated."""

        return self.action in {DecisionStatus.PAPER_TRADE, DecisionStatus.MANUAL_REVIEW}


@dataclass(frozen=True)
class BacktestConfig:
    """Configuration for the safe historical simulator."""

    initial_cash: float = 10_000.0
    position_size_pct: float = 10.0
    fee_rate: float = 0.0026
    slippage_rate: float = 0.0005
    max_bars_in_trade: int = 3
    allow_short: bool = True

    def __post_init__(self) -> None:
        if self.initial_cash <= 0:
            raise ValueError("initial_cash must be positive.")
        if self.position_size_pct <= 0 or self.position_size_pct > 100:
            raise ValueError("position_size_pct must be between 0 and 100.")
        if self.fee_rate < 0:
            raise ValueError("fee_rate cannot be negative.")
        if self.slippage_rate < 0:
            raise ValueError("slippage_rate cannot be negative.")
        if self.max_bars_in_trade < 1:
            raise ValueError("max_bars_in_trade must be at least 1.")


@dataclass(frozen=True)
class SimulatedTrade:
    """One simulated historical trade."""

    asset: str
    direction: SignalDirection
    entry_time: int
    exit_time: int
    entry_price: float
    exit_price: float
    quantity: float
    gross_pnl: float
    fees: float
    net_pnl: float
    reason: str = ""

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["direction"] = self.direction.value
        return data


@dataclass(frozen=True)
class BacktestReport:
    """Summary report generated by a backtest run."""

    asset: str
    initial_cash: float
    ending_cash: float
    total_net_pnl: float
    total_return_pct: float
    max_drawdown_pct: float
    trade_count: int
    win_count: int
    loss_count: int
    win_rate_pct: float
    profit_factor: float | None
    trades: list[SimulatedTrade] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["trades"] = [trade.to_dict() for trade in self.trades]
        return data
